### ISSUE TITLE
bug: incorrect "OraclePrivKey" encrypt

### ISSUE THREAD

**Issue by gyuguen** [medibloc/panacea-doracle#52]
We use the encryption and decryption method provided by btcec.

**crypto/encrypt.go**
```go


// Encrypt encrypts data using a secp256k1 public key (ECIES)
func Encrypt(pubKey *btcec.PublicKey, data []byte) ([]byte, error) {
	return btcec.Encrypt(pubKey, data)
}

// Decrypt decrypts data using a secp256k1 private key (ECIES)
func Decrypt(privKey *btcec.PrivateKey, data []byte) ([]byte, error) {
	return btcec.Decrypt(privKey, data)
}
```

The encryption method used here internally generates a new key every time. Therefore, even if the input is the same, the output is always different.

So you should refer to this code.
https://github.com/medibloc/doracle-poc/blob/with-panacea/pkg/secp256k1/encrypt.go#L14

example)
https://github.com/medibloc/doracle-poc/blob/with-panacea/pkg/secp256k1/encrypt_test.go#L37

**Comment by 0xHansLee** [comment]
Could you elaborate what the problem is?
AFAIK, it is right and intended to generate a new key every time to make a key pair for shared secret key temporarily. The public key is also included to encrypted data to be used to decrypt it.

ref) https://cryptobook.nakov.com/asymmetric-key-ciphers/ecdh-key-exchange

**Comment by 0xHansLee** [comment]
I missed the [issue](https://github.com/medibloc/panacea-core/issues/402) opened in `panacea-core`.
I'll also take a look at it. Thanks for reporting it!

**Comment by 0xHansLee** [comment]
There was an issue that oracles' `ConsensusValue` are different, resulting in not-consensus value due to the reason @gyuguen said.
Thus, we need to use `aes-ecc` encryption. This enables all oracles to generate the same consensus value by generating a shared key using the same key rather than creating a shared key by generating an ephemeral key (as used in `btcec.Encrypt`).

make `SharedKey` in oracle to vote : `ShareKey(oraclePrivKey, nodePubKey)`
retrieve `SharedKey` in oracle to join : `ShareKey(nodePrivKey, oraclePubKey)`

**Comment by gyuguen** [comment]
And we need a nonce value when using AES-GCM. In our example it is a random value, but we need a fixed value.
